<?php 
// Navigation Code - Common static Part
echo "
	<nav id=\"navbar\">
		<ul>
			<li><a href=\"index.php\">Home</a></li>
			<li><a href=\"jobs.php\">Jobs</a></li>
			<li><a href=\"apply.php\">Apply</a></li>
			<li><a href=\"about.php\">About Me</a></li>
			<li><a href=\"enhancements.php\">Enhancements</a></li>
      		<li><a href=\"enhancements2.php\">JS Enhancements</a></li>
      		<li><a href=\"manage.php\">HR Manager Queries</a></li>
		</ul>
	</nav> ";
?>