<?php 
// Navigation Code - Common static Part
echo "
    <h2> List of Queries </h2>
	<ul>
      <li><a href=\"manage.php#menuone\">List all EOIs</a></li>
      <li><a href=\"manage.php#menutwo\">List all EOIS for a given job reference number</a></li>
      <li><a href=\"manage.php#menuthree\">List all EOIS for a give first name,last name or both name</a></li>
      <li><a href=\"manage.php#menufive\">Delete EOIS with a specified job reference number</a></li>
      <li><a href=\"manage.php#menufour\">Change Status of EOI for particular applicant</a></li>
    </ul>
    ";

?>